//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace VeracodeService.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://analysiscenter.veracode.com/schema/2.0/applist")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/applist", IsNullable=false)]
public partial class applist {
    
    private AppType[] appField;
    
    private UserType userField;
    
    private string applist_versionField;
    
    private long account_idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("app")]
    public AppType[] app {
        get {
            return this.appField;
        }
        set {
            this.appField = value;
        }
    }
    
    /// <remarks/>
    public UserType user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string applist_version {
        get {
            return this.applist_versionField;
        }
        set {
            this.applist_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/applist")]
public partial class AppType {
    
    private long app_idField;
    
    private bool app_idFieldSpecified;
    
    private string app_nameField;
    
    private string vendor_nameField;
    
    private string policy_updated_dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long app_id {
        get {
            return this.app_idField;
        }
        set {
            this.app_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool app_idSpecified {
        get {
            return this.app_idFieldSpecified;
        }
        set {
            this.app_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string app_name {
        get {
            return this.app_nameField;
        }
        set {
            this.app_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vendor_name {
        get {
            return this.vendor_nameField;
        }
        set {
            this.vendor_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string policy_updated_date {
        get {
            return this.policy_updated_dateField;
        }
        set {
            this.policy_updated_dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/applist")]
public partial class UserType {
    
    private LoginAccountType login_account_typeField;
    
    private string usernameField;
    
    private bool create_application_profileField;
    
    private bool create_sandboxField;
    
    private bool create_new_buildField;
    
    private bool create_policy_scanField;
    
    private bool create_sandbox_scanField;
    
    private bool assign_app_to_teamField;
    
    private bool assign_app_to_any_teamField;
    
    private bool view_sandboxField;
    
    private bool view_resultsField;
    
    private bool approve_mitigationsField;
    
    private bool submit_static_scanField;
    
    private bool submit_policy_static_scanField;
    
    private bool submit_sandbox_static_scanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LoginAccountType login_account_type {
        get {
            return this.login_account_typeField;
        }
        set {
            this.login_account_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool create_application_profile {
        get {
            return this.create_application_profileField;
        }
        set {
            this.create_application_profileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool create_sandbox {
        get {
            return this.create_sandboxField;
        }
        set {
            this.create_sandboxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool create_new_build {
        get {
            return this.create_new_buildField;
        }
        set {
            this.create_new_buildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool create_policy_scan {
        get {
            return this.create_policy_scanField;
        }
        set {
            this.create_policy_scanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool create_sandbox_scan {
        get {
            return this.create_sandbox_scanField;
        }
        set {
            this.create_sandbox_scanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool assign_app_to_team {
        get {
            return this.assign_app_to_teamField;
        }
        set {
            this.assign_app_to_teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool assign_app_to_any_team {
        get {
            return this.assign_app_to_any_teamField;
        }
        set {
            this.assign_app_to_any_teamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool view_sandbox {
        get {
            return this.view_sandboxField;
        }
        set {
            this.view_sandboxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool view_results {
        get {
            return this.view_resultsField;
        }
        set {
            this.view_resultsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool approve_mitigations {
        get {
            return this.approve_mitigationsField;
        }
        set {
            this.approve_mitigationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool submit_static_scan {
        get {
            return this.submit_static_scanField;
        }
        set {
            this.submit_static_scanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool submit_policy_static_scan {
        get {
            return this.submit_policy_static_scanField;
        }
        set {
            this.submit_policy_static_scanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool submit_sandbox_static_scan {
        get {
            return this.submit_sandbox_static_scanField;
        }
        set {
            this.submit_sandbox_static_scanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/applist")]
public enum LoginAccountType {
    
    /// <remarks/>
    user,
    
    /// <remarks/>
    api,
}
}
