//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace VeracodeService.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.veracode.com/schema/reports/export/1.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0", IsNullable=false)]
public partial class detailedreport {
    
    private AnalysisType staticanalysisField;
    
    private AnalysisType dynamicanalysisField;
    
    private ManualAnalysisType manualanalysisField;
    
    private SeverityType[] severityField;
    
    private FlawStatusType flawstatusField;
    
    private CustomFieldType[] customfieldsField;
    
    private SoftwareCompositionAnalysis software_composition_analysisField;
    
    private string report_format_versionField;
    
    private long account_idField;
    
    private string app_nameField;
    
    private long app_idField;
    
    private long analysis_idField;
    
    private long static_analysis_unit_idField;
    
    private string sandbox_nameField;
    
    private long sandbox_idField;
    
    private string first_build_submitted_dateField;
    
    private string versionField;
    
    private long build_idField;
    
    private string vendorField;
    
    private string submitterField;
    
    private string platformField;
    
    private string assurance_levelField;
    
    private string business_criticalityField;
    
    private string generation_dateField;
    
    private string veracode_levelField;
    
    private string total_flawsField;
    
    private string flaws_not_mitigatedField;
    
    private string teamsField;
    
    private string life_cycle_stageField;
    
    private string planned_deployment_dateField;
    
    private string last_update_timeField;
    
    private bool is_latest_buildField;
    
    private string policy_nameField;
    
    private string policy_versionField;
    
    private string policy_compliance_statusField;
    
    private string policy_rules_statusField;
    
    private bool grace_period_expiredField;
    
    private string scan_overdueField;
    
    private string any_type_scan_dueField;
    
    private string business_ownerField;
    
    private string business_unitField;
    
    private string tagsField;
    
    private bool legacy_scan_engineField;
    
    private bool legacy_scan_engineFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("static-analysis")]
    public AnalysisType staticanalysis {
        get {
            return this.staticanalysisField;
        }
        set {
            this.staticanalysisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("dynamic-analysis")]
    public AnalysisType dynamicanalysis {
        get {
            return this.dynamicanalysisField;
        }
        set {
            this.dynamicanalysisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("manual-analysis")]
    public ManualAnalysisType manualanalysis {
        get {
            return this.manualanalysisField;
        }
        set {
            this.manualanalysisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("severity")]
    public SeverityType[] severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("flaw-status")]
    public FlawStatusType flawstatus {
        get {
            return this.flawstatusField;
        }
        set {
            this.flawstatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("customfield", IsNullable=false)]
    public CustomFieldType[] customfields {
        get {
            return this.customfieldsField;
        }
        set {
            this.customfieldsField = value;
        }
    }
    
    /// <remarks/>
    public SoftwareCompositionAnalysis software_composition_analysis {
        get {
            return this.software_composition_analysisField;
        }
        set {
            this.software_composition_analysisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string report_format_version {
        get {
            return this.report_format_versionField;
        }
        set {
            this.report_format_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string app_name {
        get {
            return this.app_nameField;
        }
        set {
            this.app_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long app_id {
        get {
            return this.app_idField;
        }
        set {
            this.app_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long analysis_id {
        get {
            return this.analysis_idField;
        }
        set {
            this.analysis_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long static_analysis_unit_id {
        get {
            return this.static_analysis_unit_idField;
        }
        set {
            this.static_analysis_unit_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sandbox_name {
        get {
            return this.sandbox_nameField;
        }
        set {
            this.sandbox_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long sandbox_id {
        get {
            return this.sandbox_idField;
        }
        set {
            this.sandbox_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string first_build_submitted_date {
        get {
            return this.first_build_submitted_dateField;
        }
        set {
            this.first_build_submitted_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long build_id {
        get {
            return this.build_idField;
        }
        set {
            this.build_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string submitter {
        get {
            return this.submitterField;
        }
        set {
            this.submitterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string assurance_level {
        get {
            return this.assurance_levelField;
        }
        set {
            this.assurance_levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string business_criticality {
        get {
            return this.business_criticalityField;
        }
        set {
            this.business_criticalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string generation_date {
        get {
            return this.generation_dateField;
        }
        set {
            this.generation_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string veracode_level {
        get {
            return this.veracode_levelField;
        }
        set {
            this.veracode_levelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string total_flaws {
        get {
            return this.total_flawsField;
        }
        set {
            this.total_flawsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string flaws_not_mitigated {
        get {
            return this.flaws_not_mitigatedField;
        }
        set {
            this.flaws_not_mitigatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string teams {
        get {
            return this.teamsField;
        }
        set {
            this.teamsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string life_cycle_stage {
        get {
            return this.life_cycle_stageField;
        }
        set {
            this.life_cycle_stageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string planned_deployment_date {
        get {
            return this.planned_deployment_dateField;
        }
        set {
            this.planned_deployment_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string last_update_time {
        get {
            return this.last_update_timeField;
        }
        set {
            this.last_update_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool is_latest_build {
        get {
            return this.is_latest_buildField;
        }
        set {
            this.is_latest_buildField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string policy_name {
        get {
            return this.policy_nameField;
        }
        set {
            this.policy_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string policy_version {
        get {
            return this.policy_versionField;
        }
        set {
            this.policy_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string policy_compliance_status {
        get {
            return this.policy_compliance_statusField;
        }
        set {
            this.policy_compliance_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string policy_rules_status {
        get {
            return this.policy_rules_statusField;
        }
        set {
            this.policy_rules_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool grace_period_expired {
        get {
            return this.grace_period_expiredField;
        }
        set {
            this.grace_period_expiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scan_overdue {
        get {
            return this.scan_overdueField;
        }
        set {
            this.scan_overdueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string any_type_scan_due {
        get {
            return this.any_type_scan_dueField;
        }
        set {
            this.any_type_scan_dueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string business_owner {
        get {
            return this.business_ownerField;
        }
        set {
            this.business_ownerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string business_unit {
        get {
            return this.business_unitField;
        }
        set {
            this.business_unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tags {
        get {
            return this.tagsField;
        }
        set {
            this.tagsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool legacy_scan_engine {
        get {
            return this.legacy_scan_engineField;
        }
        set {
            this.legacy_scan_engineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool legacy_scan_engineSpecified {
        get {
            return this.legacy_scan_engineFieldSpecified;
        }
        set {
            this.legacy_scan_engineFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class AnalysisType {
    
    private DetailedReportModuleType[] modulesField;
    
    private string ratingField;
    
    private string scoreField;
    
    private string mitigated_ratingField;
    
    private string mitigated_scoreField;
    
    private string submitted_dateField;
    
    private string published_dateField;
    
    private string next_scan_dueField;
    
    private long analysis_size_bytesField;
    
    private bool analysis_size_bytesFieldSpecified;
    
    private string engine_versionField;
    
    private DetailedReportDynamicScanType dynamic_scan_typeField;
    
    private bool dynamic_scan_typeFieldSpecified;
    
    private string scan_exit_status_idField;
    
    private string scan_exit_status_descField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("module", IsNullable=false)]
    public DetailedReportModuleType[] modules {
        get {
            return this.modulesField;
        }
        set {
            this.modulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigated_rating {
        get {
            return this.mitigated_ratingField;
        }
        set {
            this.mitigated_ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string mitigated_score {
        get {
            return this.mitigated_scoreField;
        }
        set {
            this.mitigated_scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string submitted_date {
        get {
            return this.submitted_dateField;
        }
        set {
            this.submitted_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string published_date {
        get {
            return this.published_dateField;
        }
        set {
            this.published_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string next_scan_due {
        get {
            return this.next_scan_dueField;
        }
        set {
            this.next_scan_dueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long analysis_size_bytes {
        get {
            return this.analysis_size_bytesField;
        }
        set {
            this.analysis_size_bytesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool analysis_size_bytesSpecified {
        get {
            return this.analysis_size_bytesFieldSpecified;
        }
        set {
            this.analysis_size_bytesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string engine_version {
        get {
            return this.engine_versionField;
        }
        set {
            this.engine_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DetailedReportDynamicScanType dynamic_scan_type {
        get {
            return this.dynamic_scan_typeField;
        }
        set {
            this.dynamic_scan_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dynamic_scan_typeSpecified {
        get {
            return this.dynamic_scan_typeFieldSpecified;
        }
        set {
            this.dynamic_scan_typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string scan_exit_status_id {
        get {
            return this.scan_exit_status_idField;
        }
        set {
            this.scan_exit_status_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scan_exit_status_desc {
        get {
            return this.scan_exit_status_descField;
        }
        set {
            this.scan_exit_status_descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class DetailedReportModuleType {
    
    private string nameField;
    
    private string compilerField;
    
    private string osField;
    
    private string architectureField;
    
    private string locField;
    
    private string scoreField;
    
    private string numflawssev0Field;
    
    private string numflawssev1Field;
    
    private string numflawssev2Field;
    
    private string numflawssev3Field;
    
    private string numflawssev4Field;
    
    private string numflawssev5Field;
    
    private string target_urlField;
    
    private string domainField;
    
    private string approxlinecountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string compiler {
        get {
            return this.compilerField;
        }
        set {
            this.compilerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string os {
        get {
            return this.osField;
        }
        set {
            this.osField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string architecture {
        get {
            return this.architectureField;
        }
        set {
            this.architectureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string loc {
        get {
            return this.locField;
        }
        set {
            this.locField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numflawssev0 {
        get {
            return this.numflawssev0Field;
        }
        set {
            this.numflawssev0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numflawssev1 {
        get {
            return this.numflawssev1Field;
        }
        set {
            this.numflawssev1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numflawssev2 {
        get {
            return this.numflawssev2Field;
        }
        set {
            this.numflawssev2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numflawssev3 {
        get {
            return this.numflawssev3Field;
        }
        set {
            this.numflawssev3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numflawssev4 {
        get {
            return this.numflawssev4Field;
        }
        set {
            this.numflawssev4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string numflawssev5 {
        get {
            return this.numflawssev5Field;
        }
        set {
            this.numflawssev5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string target_url {
        get {
            return this.target_urlField;
        }
        set {
            this.target_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string domain {
        get {
            return this.domainField;
        }
        set {
            this.domainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string approxlinecount {
        get {
            return this.approxlinecountField;
        }
        set {
            this.approxlinecountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class PolicyRule {
    
    private PolicyRuleType typeField;
    
    private string valueField;
    
    private string descField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PolicyRuleType type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public enum PolicyRuleType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disallow Vulnerabilities by Severity")]
    DisallowVulnerabilitiesbySeverity,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disallow CVSS Score")]
    DisallowCVSSScore,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disallow Component Blacklist")]
    DisallowComponentBlacklist,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Disallow Component by License Risk")]
    DisallowComponentbyLicenseRisk,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class Vulnerability {
    
    private string cve_idField;
    
    private double cvss_scoreField;
    
    private string severityField;
    
    private string cwe_idField;
    
    private string first_found_dateField;
    
    private string cve_summaryField;
    
    private string severity_descField;
    
    private string mitigationField;
    
    private string mitigation_typeField;
    
    private string mitigated_dateField;
    
    private string vulnerability_affects_policy_complianceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cve_id {
        get {
            return this.cve_idField;
        }
        set {
            this.cve_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double cvss_score {
        get {
            return this.cvss_scoreField;
        }
        set {
            this.cvss_scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cwe_id {
        get {
            return this.cwe_idField;
        }
        set {
            this.cwe_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string first_found_date {
        get {
            return this.first_found_dateField;
        }
        set {
            this.first_found_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cve_summary {
        get {
            return this.cve_summaryField;
        }
        set {
            this.cve_summaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string severity_desc {
        get {
            return this.severity_descField;
        }
        set {
            this.severity_descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigation {
        get {
            return this.mitigationField;
        }
        set {
            this.mitigationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigation_type {
        get {
            return this.mitigation_typeField;
        }
        set {
            this.mitigation_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigated_date {
        get {
            return this.mitigated_dateField;
        }
        set {
            this.mitigated_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vulnerability_affects_policy_compliance {
        get {
            return this.vulnerability_affects_policy_complianceField;
        }
        set {
            this.vulnerability_affects_policy_complianceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class License {
    
    private string nameField;
    
    private string spdx_idField;
    
    private string license_urlField;
    
    private string risk_ratingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string spdx_id {
        get {
            return this.spdx_idField;
        }
        set {
            this.spdx_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string license_url {
        get {
            return this.license_urlField;
        }
        set {
            this.license_urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string risk_rating {
        get {
            return this.risk_ratingField;
        }
        set {
            this.risk_ratingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class FilePath {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class Component {
    
    private FilePath[] file_pathsField;
    
    private License[] licensesField;
    
    private Vulnerability[] vulnerabilitiesField;
    
    private PolicyRule[] violated_policy_rulesField;
    
    private string component_idField;
    
    private string file_nameField;
    
    private string sha1Field;
    
    private string vulnerabilities1Field;
    
    private string max_cvss_scoreField;
    
    private string libraryField;
    
    private string versionField;
    
    private string vendorField;
    
    private string descriptionField;
    
    private string blacklistedField;
    
    private string newField;
    
    private string added_dateField;
    
    private string component_affects_policy_complianceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("file_path", IsNullable=false)]
    public FilePath[] file_paths {
        get {
            return this.file_pathsField;
        }
        set {
            this.file_pathsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("license", IsNullable=false)]
    public License[] licenses {
        get {
            return this.licensesField;
        }
        set {
            this.licensesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("vulnerability", IsNullable=false)]
    public Vulnerability[] vulnerabilities {
        get {
            return this.vulnerabilitiesField;
        }
        set {
            this.vulnerabilitiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("policy_rule", IsNullable=false)]
    public PolicyRule[] violated_policy_rules {
        get {
            return this.violated_policy_rulesField;
        }
        set {
            this.violated_policy_rulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string component_id {
        get {
            return this.component_idField;
        }
        set {
            this.component_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string file_name {
        get {
            return this.file_nameField;
        }
        set {
            this.file_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sha1 {
        get {
            return this.sha1Field;
        }
        set {
            this.sha1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("vulnerabilities", DataType="integer")]
    public string vulnerabilities1 {
        get {
            return this.vulnerabilities1Field;
        }
        set {
            this.vulnerabilities1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string max_cvss_score {
        get {
            return this.max_cvss_scoreField;
        }
        set {
            this.max_cvss_scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string library {
        get {
            return this.libraryField;
        }
        set {
            this.libraryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vendor {
        get {
            return this.vendorField;
        }
        set {
            this.vendorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string blacklisted {
        get {
            return this.blacklistedField;
        }
        set {
            this.blacklistedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @new {
        get {
            return this.newField;
        }
        set {
            this.newField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string added_date {
        get {
            return this.added_dateField;
        }
        set {
            this.added_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string component_affects_policy_compliance {
        get {
            return this.component_affects_policy_complianceField;
        }
        set {
            this.component_affects_policy_complianceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class SoftwareCompositionAnalysis {
    
    private Component[] vulnerable_componentsField;
    
    private string third_party_componentsField;
    
    private bool violate_policyField;
    
    private string components_violated_policyField;
    
    private string blacklisted_componentsField;
    
    private bool sca_service_availableField;
    
    private bool sca_service_availableFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("component", IsNullable=false)]
    public Component[] vulnerable_components {
        get {
            return this.vulnerable_componentsField;
        }
        set {
            this.vulnerable_componentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string third_party_components {
        get {
            return this.third_party_componentsField;
        }
        set {
            this.third_party_componentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool violate_policy {
        get {
            return this.violate_policyField;
        }
        set {
            this.violate_policyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string components_violated_policy {
        get {
            return this.components_violated_policyField;
        }
        set {
            this.components_violated_policyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string blacklisted_components {
        get {
            return this.blacklisted_componentsField;
        }
        set {
            this.blacklisted_componentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool sca_service_available {
        get {
            return this.sca_service_availableField;
        }
        set {
            this.sca_service_availableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sca_service_availableSpecified {
        get {
            return this.sca_service_availableFieldSpecified;
        }
        set {
            this.sca_service_availableFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class CustomFieldType {
    
    private string nameField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class FlawStatusType {
    
    private string newField;
    
    private string reopenField;
    
    private string openField;
    
    private string cannotreproduceField;
    
    private string fixedField;
    
    private string totalField;
    
    private string not_mitigatedField;
    
    private string sev1changeField;
    
    private string sev2changeField;
    
    private string sev3changeField;
    
    private string sev4changeField;
    
    private string sev5changeField;
    
    private string conformstoguidelinesField;
    
    private string deviatesfromguidelinesField;
    
    private string totalreviewedmitigationsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string @new {
        get {
            return this.newField;
        }
        set {
            this.newField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string reopen {
        get {
            return this.reopenField;
        }
        set {
            this.reopenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string open {
        get {
            return this.openField;
        }
        set {
            this.openField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("cannot-reproduce", DataType="integer")]
    public string cannotreproduce {
        get {
            return this.cannotreproduceField;
        }
        set {
            this.cannotreproduceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string @fixed {
        get {
            return this.fixedField;
        }
        set {
            this.fixedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string total {
        get {
            return this.totalField;
        }
        set {
            this.totalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string not_mitigated {
        get {
            return this.not_mitigatedField;
        }
        set {
            this.not_mitigatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sev-1-change", DataType="integer")]
    public string sev1change {
        get {
            return this.sev1changeField;
        }
        set {
            this.sev1changeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sev-2-change", DataType="integer")]
    public string sev2change {
        get {
            return this.sev2changeField;
        }
        set {
            this.sev2changeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sev-3-change", DataType="integer")]
    public string sev3change {
        get {
            return this.sev3changeField;
        }
        set {
            this.sev3changeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sev-4-change", DataType="integer")]
    public string sev4change {
        get {
            return this.sev4changeField;
        }
        set {
            this.sev4changeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("sev-5-change", DataType="integer")]
    public string sev5change {
        get {
            return this.sev5changeField;
        }
        set {
            this.sev5changeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("conforms-to-guidelines", DataType="integer")]
    public string conformstoguidelines {
        get {
            return this.conformstoguidelinesField;
        }
        set {
            this.conformstoguidelinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("deviates-from-guidelines", DataType="integer")]
    public string deviatesfromguidelines {
        get {
            return this.deviatesfromguidelinesField;
        }
        set {
            this.deviatesfromguidelinesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute("total-reviewed-mitigations", DataType="integer")]
    public string totalreviewedmitigations {
        get {
            return this.totalreviewedmitigationsField;
        }
        set {
            this.totalreviewedmitigationsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class ScreenshotType {
    
    private byte[] dataField;
    
    private ScreenshotFormatType formatField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ScreenshotFormatType format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public enum ScreenshotFormatType {
    
    /// <remarks/>
    GIF,
    
    /// <remarks/>
    JPG,
    
    /// <remarks/>
    PNG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class AppendixType {
    
    private string descriptionField;
    
    private ScreenshotType[] screenshotField;
    
    private string[] codeField;
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("screenshot")]
    public ScreenshotType[] screenshot {
        get {
            return this.screenshotField;
        }
        set {
            this.screenshotField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("code")]
    public string[] code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class AnnotationType {
    
    private string actionField;
    
    private string descriptionField;
    
    private string userField;
    
    private string dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class ExploitAdjustmentType {
    
    private string noteField;
    
    private int score_adjustmentField;
    
    /// <remarks/>
    public string note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int score_adjustment {
        get {
            return this.score_adjustmentField;
        }
        set {
            this.score_adjustmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class MitigationType {
    
    private string actionField;
    
    private string descriptionField;
    
    private string userField;
    
    private string dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class FlawType {
    
    private MitigationType[] mitigationsField;
    
    private ExploitAdjustmentType[] exploitability_adjustmentsField;
    
    private AnnotationType[] annotationsField;
    
    private string exploit_descField;
    
    private string severity_descField;
    
    private string remediation_descField;
    
    private AppendixType appendixField;
    
    private string severityField;
    
    private string categorynameField;
    
    private string countField;
    
    private string issueidField;
    
    private string moduleField;
    
    private string typeField;
    
    private string descriptionField;
    
    private string noteField;
    
    private string cweidField;
    
    private string remediationeffortField;
    
    private string exploitLevelField;
    
    private string categoryidField;
    
    private bool pcirelatedField;
    
    private bool pcirelatedFieldSpecified;
    
    private string date_first_occurrenceField;
    
    private string remediation_statusField;
    
    private string sourcefileField;
    
    private string lineField;
    
    private string sourcefilepathField;
    
    private string scopeField;
    
    private string functionprototypeField;
    
    private string functionrelativelocationField;
    
    private string urlField;
    
    private string vuln_parameterField;
    
    private string procedure_nameField;
    
    private string procedure_hashField;
    
    private string prototype_hashField;
    
    private string statement_hashField;
    
    private string statement_hash_countField;
    
    private string statement_hash_ordinalField;
    
    private string locationField;
    
    private decimal cvssField;
    
    private bool cvssFieldSpecified;
    
    private string capecidField;
    
    private int exploitdifficultyField;
    
    private bool exploitdifficultyFieldSpecified;
    
    private string inputvectorField;
    
    private string cia_impactField;
    
    private string grace_period_expiresField;
    
    private bool affects_policy_complianceField;
    
    private string mitigation_statusField;
    
    private string mitigation_status_descField;
    
    private string tagField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("mitigation", IsNullable=false)]
    public MitigationType[] mitigations {
        get {
            return this.mitigationsField;
        }
        set {
            this.mitigationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("exploitability_adjustment", IsNullable=false)]
    public ExploitAdjustmentType[] exploitability_adjustments {
        get {
            return this.exploitability_adjustmentsField;
        }
        set {
            this.exploitability_adjustmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("annotation", IsNullable=false)]
    public AnnotationType[] annotations {
        get {
            return this.annotationsField;
        }
        set {
            this.annotationsField = value;
        }
    }
    
    /// <remarks/>
    public string exploit_desc {
        get {
            return this.exploit_descField;
        }
        set {
            this.exploit_descField = value;
        }
    }
    
    /// <remarks/>
    public string severity_desc {
        get {
            return this.severity_descField;
        }
        set {
            this.severity_descField = value;
        }
    }
    
    /// <remarks/>
    public string remediation_desc {
        get {
            return this.remediation_descField;
        }
        set {
            this.remediation_descField = value;
        }
    }
    
    /// <remarks/>
    public AppendixType appendix {
        get {
            return this.appendixField;
        }
        set {
            this.appendixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string categoryname {
        get {
            return this.categorynameField;
        }
        set {
            this.categorynameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string issueid {
        get {
            return this.issueidField;
        }
        set {
            this.issueidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string cweid {
        get {
            return this.cweidField;
        }
        set {
            this.cweidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string remediationeffort {
        get {
            return this.remediationeffortField;
        }
        set {
            this.remediationeffortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string exploitLevel {
        get {
            return this.exploitLevelField;
        }
        set {
            this.exploitLevelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string categoryid {
        get {
            return this.categoryidField;
        }
        set {
            this.categoryidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool pcirelated {
        get {
            return this.pcirelatedField;
        }
        set {
            this.pcirelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pcirelatedSpecified {
        get {
            return this.pcirelatedFieldSpecified;
        }
        set {
            this.pcirelatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date_first_occurrence {
        get {
            return this.date_first_occurrenceField;
        }
        set {
            this.date_first_occurrenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string remediation_status {
        get {
            return this.remediation_statusField;
        }
        set {
            this.remediation_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sourcefile {
        get {
            return this.sourcefileField;
        }
        set {
            this.sourcefileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string line {
        get {
            return this.lineField;
        }
        set {
            this.lineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sourcefilepath {
        get {
            return this.sourcefilepathField;
        }
        set {
            this.sourcefilepathField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string scope {
        get {
            return this.scopeField;
        }
        set {
            this.scopeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string functionprototype {
        get {
            return this.functionprototypeField;
        }
        set {
            this.functionprototypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string functionrelativelocation {
        get {
            return this.functionrelativelocationField;
        }
        set {
            this.functionrelativelocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vuln_parameter {
        get {
            return this.vuln_parameterField;
        }
        set {
            this.vuln_parameterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string procedure_name {
        get {
            return this.procedure_nameField;
        }
        set {
            this.procedure_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string procedure_hash {
        get {
            return this.procedure_hashField;
        }
        set {
            this.procedure_hashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prototype_hash {
        get {
            return this.prototype_hashField;
        }
        set {
            this.prototype_hashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string statement_hash {
        get {
            return this.statement_hashField;
        }
        set {
            this.statement_hashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string statement_hash_count {
        get {
            return this.statement_hash_countField;
        }
        set {
            this.statement_hash_countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string statement_hash_ordinal {
        get {
            return this.statement_hash_ordinalField;
        }
        set {
            this.statement_hash_ordinalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string location {
        get {
            return this.locationField;
        }
        set {
            this.locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal cvss {
        get {
            return this.cvssField;
        }
        set {
            this.cvssField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool cvssSpecified {
        get {
            return this.cvssFieldSpecified;
        }
        set {
            this.cvssFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string capecid {
        get {
            return this.capecidField;
        }
        set {
            this.capecidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int exploitdifficulty {
        get {
            return this.exploitdifficultyField;
        }
        set {
            this.exploitdifficultyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool exploitdifficultySpecified {
        get {
            return this.exploitdifficultyFieldSpecified;
        }
        set {
            this.exploitdifficultyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string inputvector {
        get {
            return this.inputvectorField;
        }
        set {
            this.inputvectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cia_impact {
        get {
            return this.cia_impactField;
        }
        set {
            this.cia_impactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string grace_period_expires {
        get {
            return this.grace_period_expiresField;
        }
        set {
            this.grace_period_expiresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool affects_policy_compliance {
        get {
            return this.affects_policy_complianceField;
        }
        set {
            this.affects_policy_complianceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigation_status {
        get {
            return this.mitigation_statusField;
        }
        set {
            this.mitigation_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigation_status_desc {
        get {
            return this.mitigation_status_descField;
        }
        set {
            this.mitigation_status_descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tag {
        get {
            return this.tagField;
        }
        set {
            this.tagField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class CweType {
    
    private CweTypeText[] descriptionField;
    
    private FlawType[] staticflawsField;
    
    private FlawType[] dynamicflawsField;
    
    private FlawType[] manualflawsField;
    
    private string cweidField;
    
    private string cwenameField;
    
    private bool pcirelatedField;
    
    private bool pcirelatedFieldSpecified;
    
    private string owaspField;
    
    private string owasp2013Field;
    
    private string sansField;
    
    private string certcField;
    
    private string certcppField;
    
    private string certjavaField;
    
    private string owaspmobileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("text", IsNullable=false)]
    public CweTypeText[] description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("flaw", IsNullable=false)]
    public FlawType[] staticflaws {
        get {
            return this.staticflawsField;
        }
        set {
            this.staticflawsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("flaw", IsNullable=false)]
    public FlawType[] dynamicflaws {
        get {
            return this.dynamicflawsField;
        }
        set {
            this.dynamicflawsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("flaw", IsNullable=false)]
    public FlawType[] manualflaws {
        get {
            return this.manualflawsField;
        }
        set {
            this.manualflawsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string cweid {
        get {
            return this.cweidField;
        }
        set {
            this.cweidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cwename {
        get {
            return this.cwenameField;
        }
        set {
            this.cwenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool pcirelated {
        get {
            return this.pcirelatedField;
        }
        set {
            this.pcirelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pcirelatedSpecified {
        get {
            return this.pcirelatedFieldSpecified;
        }
        set {
            this.pcirelatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string owasp {
        get {
            return this.owaspField;
        }
        set {
            this.owaspField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string owasp2013 {
        get {
            return this.owasp2013Field;
        }
        set {
            this.owasp2013Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string sans {
        get {
            return this.sansField;
        }
        set {
            this.sansField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string certc {
        get {
            return this.certcField;
        }
        set {
            this.certcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string certcpp {
        get {
            return this.certcppField;
        }
        set {
            this.certcppField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string certjava {
        get {
            return this.certjavaField;
        }
        set {
            this.certjavaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
    public string owaspmobile {
        get {
            return this.owaspmobileField;
        }
        set {
            this.owaspmobileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class CweTypeText {
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class BulletItemType {
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class ParaType {
    
    private BulletItemType[] bulletitemField;
    
    private string textField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("bulletitem")]
    public BulletItemType[] bulletitem {
        get {
            return this.bulletitemField;
        }
        set {
            this.bulletitemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class CategoryType {
    
    private ParaType[] descField;
    
    private ParaType[] recommendationsField;
    
    private CweType[] cweField;
    
    private string categoryidField;
    
    private string categorynameField;
    
    private bool pcirelatedField;
    
    private bool pcirelatedFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("para", IsNullable=false)]
    public ParaType[] desc {
        get {
            return this.descField;
        }
        set {
            this.descField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("para", IsNullable=false)]
    public ParaType[] recommendations {
        get {
            return this.recommendationsField;
        }
        set {
            this.recommendationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("cwe")]
    public CweType[] cwe {
        get {
            return this.cweField;
        }
        set {
            this.cweField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string categoryid {
        get {
            return this.categoryidField;
        }
        set {
            this.categoryidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string categoryname {
        get {
            return this.categorynameField;
        }
        set {
            this.categorynameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool pcirelated {
        get {
            return this.pcirelatedField;
        }
        set {
            this.pcirelatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pcirelatedSpecified {
        get {
            return this.pcirelatedFieldSpecified;
        }
        set {
            this.pcirelatedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class SeverityType {
    
    private CategoryType[] categoryField;
    
    private string levelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("category")]
    public CategoryType[] category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string level {
        get {
            return this.levelField;
        }
        set {
            this.levelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public partial class ManualAnalysisType {
    
    private string cia_adjustmentField;
    
    private string[] delivery_consultantField;
    
    private DetailedReportModuleType[] modulesField;
    
    private string ratingField;
    
    private string scoreField;
    
    private string mitigated_ratingField;
    
    private string mitigated_scoreField;
    
    private string submitted_dateField;
    
    private string published_dateField;
    
    private string next_scan_dueField;
    
    private string versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonPositiveInteger")]
    public string cia_adjustment {
        get {
            return this.cia_adjustmentField;
        }
        set {
            this.cia_adjustmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("delivery_consultant")]
    public string[] delivery_consultant {
        get {
            return this.delivery_consultantField;
        }
        set {
            this.delivery_consultantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("module", IsNullable=false)]
    public DetailedReportModuleType[] modules {
        get {
            return this.modulesField;
        }
        set {
            this.modulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mitigated_rating {
        get {
            return this.mitigated_ratingField;
        }
        set {
            this.mitigated_ratingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string mitigated_score {
        get {
            return this.mitigated_scoreField;
        }
        set {
            this.mitigated_scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string submitted_date {
        get {
            return this.submitted_dateField;
        }
        set {
            this.submitted_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string published_date {
        get {
            return this.published_dateField;
        }
        set {
            this.published_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string next_scan_due {
        get {
            return this.next_scan_dueField;
        }
        set {
            this.next_scan_dueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.veracode.com/schema/reports/export/1.0")]
public enum DetailedReportDynamicScanType {
    
    /// <remarks/>
    mp,
    
    /// <remarks/>
    ds,
    
    /// <remarks/>
    da,
}
    }
