//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace VeracodeService.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://analysiscenter.veracode.com/schema/2.0/filelist")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/filelist", IsNullable=false)]
public partial class filelist {
    
    private FileListFileType[] fileField;
    
    private string filelist_versionField;
    
    private long account_idField;
    
    private bool account_idFieldSpecified;
    
    private long app_idField;
    
    private bool app_idFieldSpecified;
    
    private long sandbox_idField;
    
    private bool sandbox_idFieldSpecified;
    
    private long build_idField;
    
    private bool build_idFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("file")]
    public FileListFileType[] file {
        get {
            return this.fileField;
        }
        set {
            this.fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filelist_version {
        get {
            return this.filelist_versionField;
        }
        set {
            this.filelist_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool account_idSpecified {
        get {
            return this.account_idFieldSpecified;
        }
        set {
            this.account_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long app_id {
        get {
            return this.app_idField;
        }
        set {
            this.app_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool app_idSpecified {
        get {
            return this.app_idFieldSpecified;
        }
        set {
            this.app_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long sandbox_id {
        get {
            return this.sandbox_idField;
        }
        set {
            this.sandbox_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sandbox_idSpecified {
        get {
            return this.sandbox_idFieldSpecified;
        }
        set {
            this.sandbox_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long build_id {
        get {
            return this.build_idField;
        }
        set {
            this.build_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool build_idSpecified {
        get {
            return this.build_idFieldSpecified;
        }
        set {
            this.build_idFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/filelist")]
public partial class FileListFileType {
    
    private long file_idField;
    
    private bool file_idFieldSpecified;
    
    private string file_nameField;
    
    private StatusType file_statusField;
    
    private bool file_statusFieldSpecified;
    
    private string file_md5Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long file_id {
        get {
            return this.file_idField;
        }
        set {
            this.file_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool file_idSpecified {
        get {
            return this.file_idFieldSpecified;
        }
        set {
            this.file_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string file_name {
        get {
            return this.file_nameField;
        }
        set {
            this.file_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public StatusType file_status {
        get {
            return this.file_statusField;
        }
        set {
            this.file_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool file_statusSpecified {
        get {
            return this.file_statusFieldSpecified;
        }
        set {
            this.file_statusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string file_md5 {
        get {
            return this.file_md5Field;
        }
        set {
            this.file_md5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/filelist")]
public enum StatusType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Pending Upload")]
    PendingUpload,
    
    /// <remarks/>
    Uploading,
    
    /// <remarks/>
    Purged,
    
    /// <remarks/>
    Uploaded,
    
    /// <remarks/>
    Missing,
    
    /// <remarks/>
    Partial,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid Checksum")]
    InvalidChecksum,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Invalid Archive")]
    InvalidArchive,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Archive File Within Another Archive")]
    ArchiveFileWithinAnotherArchive,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Archive File with Unsupported Compression")]
    ArchiveFilewithUnsupportedCompression,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Archive File is Password Protected")]
    ArchiveFileisPasswordProtected,
}
}
