//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

namespace VeracodeService.Models
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults", IsNullable=false)]
public partial class prescanresults {
    
    private ModuleType[] moduleField;
    
    private string prescanresults_versionField;
    
    private long account_idField;
    
    private bool account_idFieldSpecified;
    
    private long app_idField;
    
    private bool app_idFieldSpecified;
    
    private long sandbox_idField;
    
    private bool sandbox_idFieldSpecified;
    
    private long build_idField;
    
    private bool build_idFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("module")]
    public ModuleType[] module {
        get {
            return this.moduleField;
        }
        set {
            this.moduleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string prescanresults_version {
        get {
            return this.prescanresults_versionField;
        }
        set {
            this.prescanresults_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool account_idSpecified {
        get {
            return this.account_idFieldSpecified;
        }
        set {
            this.account_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long app_id {
        get {
            return this.app_idField;
        }
        set {
            this.app_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool app_idSpecified {
        get {
            return this.app_idFieldSpecified;
        }
        set {
            this.app_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long sandbox_id {
        get {
            return this.sandbox_idField;
        }
        set {
            this.sandbox_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool sandbox_idSpecified {
        get {
            return this.sandbox_idFieldSpecified;
        }
        set {
            this.sandbox_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long build_id {
        get {
            return this.build_idField;
        }
        set {
            this.build_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool build_idSpecified {
        get {
            return this.build_idFieldSpecified;
        }
        set {
            this.build_idFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults")]
public partial class ModuleType {
    
    private IssueType[] issueField;
    
    private FileIssueType[] file_issueField;
    
    private SourceFileType sourcefileField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string nameField;
    
    private long app_file_idField;
    
    private bool app_file_idFieldSpecified;
    
    private string checksumField;
    
    private string platformField;
    
    private string sizeField;
    
    private string statusField;
    
    private bool has_fatal_errorsField;
    
    private bool has_fatal_errorsFieldSpecified;
    
    private bool is_dependencyField;
    
    private bool is_dependencyFieldSpecified;
    
    private string differenceField;
    
    public ModuleType() {
        this.differenceField = "unmodified";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("issue")]
    public IssueType[] issue {
        get {
            return this.issueField;
        }
        set {
            this.issueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("file_issue")]
    public FileIssueType[] file_issue {
        get {
            return this.file_issueField;
        }
        set {
            this.file_issueField = value;
        }
    }
    
    /// <remarks/>
    public SourceFileType sourcefile {
        get {
            return this.sourcefileField;
        }
        set {
            this.sourcefileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long app_file_id {
        get {
            return this.app_file_idField;
        }
        set {
            this.app_file_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool app_file_idSpecified {
        get {
            return this.app_file_idFieldSpecified;
        }
        set {
            this.app_file_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string checksum {
        get {
            return this.checksumField;
        }
        set {
            this.checksumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string platform {
        get {
            return this.platformField;
        }
        set {
            this.platformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool has_fatal_errors {
        get {
            return this.has_fatal_errorsField;
        }
        set {
            this.has_fatal_errorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool has_fatal_errorsSpecified {
        get {
            return this.has_fatal_errorsFieldSpecified;
        }
        set {
            this.has_fatal_errorsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool is_dependency {
        get {
            return this.is_dependencyField;
        }
        set {
            this.is_dependencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool is_dependencySpecified {
        get {
            return this.is_dependencyFieldSpecified;
        }
        set {
            this.is_dependencyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("unmodified")]
    public string difference {
        get {
            return this.differenceField;
        }
        set {
            this.differenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults")]
public partial class IssueType {
    
    private string detailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults")]
public partial class FileType {
    
    private string pathField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path {
        get {
            return this.pathField;
        }
        set {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults")]
public partial class SourceFileType {
    
    private FileType[] modifiedField;
    
    private FileType[] newField;
    
    private FileType[] removedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
    public FileType[] modified {
        get {
            return this.modifiedField;
        }
        set {
            this.modifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
    public FileType[] @new {
        get {
            return this.newField;
        }
        set {
            this.newField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
    public FileType[] removed {
        get {
            return this.removedField;
        }
        set {
            this.removedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/2.0/prescanresults")]
public partial class FileIssueType {
    
    private string filenameField;
    
    private string detailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filename {
        get {
            return this.filenameField;
        }
        set {
            this.filenameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}}
