//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://analysiscenter.veracode.com/schema/teaminfo/3.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://analysiscenter.veracode.com/schema/teaminfo/3.0", IsNullable=false)]
public partial class teaminfo {
    
    private teaminfoUsers[] usersField;
    
    private UserType[] userField;
    
    private TeamInfoAppType[] applicationField;
    
    private string account_idField;
    
    private decimal teaminfo_versionField;
    
    private bool teaminfo_versionFieldSpecified;
    
    private string team_idField;
    
    private string team_nameField;
    
    private bool can_view_shared_typesField;
    
    private bool can_view_shared_typesFieldSpecified;
    
    private string business_unitField;
    
    private string creation_dateField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("users")]
    public teaminfoUsers[] users {
        get {
            return this.usersField;
        }
        set {
            this.usersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("user")]
    public UserType[] user {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("application")]
    public TeamInfoAppType[] application {
        get {
            return this.applicationField;
        }
        set {
            this.applicationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal teaminfo_version {
        get {
            return this.teaminfo_versionField;
        }
        set {
            this.teaminfo_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool teaminfo_versionSpecified {
        get {
            return this.teaminfo_versionFieldSpecified;
        }
        set {
            this.teaminfo_versionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string team_id {
        get {
            return this.team_idField;
        }
        set {
            this.team_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string team_name {
        get {
            return this.team_nameField;
        }
        set {
            this.team_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool can_view_shared_types {
        get {
            return this.can_view_shared_typesField;
        }
        set {
            this.can_view_shared_typesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool can_view_shared_typesSpecified {
        get {
            return this.can_view_shared_typesFieldSpecified;
        }
        set {
            this.can_view_shared_typesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string business_unit {
        get {
            return this.business_unitField;
        }
        set {
            this.business_unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string creation_date {
        get {
            return this.creation_dateField;
        }
        set {
            this.creation_dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://analysiscenter.veracode.com/schema/teaminfo/3.0")]
public partial class teaminfoUsers {
    
    private string usernamesField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usernames {
        get {
            return this.usernamesField;
        }
        set {
            this.usernamesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/teaminfo/3.0")]
public partial class TeamInfoAppType {
    
    private long app_idField;
    
    private bool app_idFieldSpecified;
    
    private string app_nameField;
    
    private string assessment_typeField;
    
    private long account_idField;
    
    private bool account_idFieldSpecified;
    
    private string business_unitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long app_id {
        get {
            return this.app_idField;
        }
        set {
            this.app_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool app_idSpecified {
        get {
            return this.app_idFieldSpecified;
        }
        set {
            this.app_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string app_name {
        get {
            return this.app_nameField;
        }
        set {
            this.app_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string assessment_type {
        get {
            return this.assessment_typeField;
        }
        set {
            this.assessment_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool account_idSpecified {
        get {
            return this.account_idFieldSpecified;
        }
        set {
            this.account_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string business_unit {
        get {
            return this.business_unitField;
        }
        set {
            this.business_unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/teaminfo/3.0")]
public partial class UserType {
    
    private string usernameField;
    
    private string first_nameField;
    
    private string last_nameField;
    
    private string email_addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string first_name {
        get {
            return this.first_nameField;
        }
        set {
            this.first_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string last_name {
        get {
            return this.last_nameField;
        }
        set {
            this.last_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email_address {
        get {
            return this.email_addressField;
        }
        set {
            this.email_addressField = value;
        }
    }
}
