//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://analysiscenter.veracode.com/schema/userlist/3.0")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="https://analysiscenter.veracode.com/schema/userlist/3.0", IsNullable=false)]
public partial class userlist {
    
    private Filters filtersField;
    
    private UserList usersField;
    
    private long account_idField;
    
    private bool account_idFieldSpecified;
    
    private decimal userlist_versionField;
    
    private bool userlist_versionFieldSpecified;
    
    /// <remarks/>
    public Filters filters {
        get {
            return this.filtersField;
        }
        set {
            this.filtersField = value;
        }
    }
    
    /// <remarks/>
    public UserList users {
        get {
            return this.usersField;
        }
        set {
            this.usersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool account_idSpecified {
        get {
            return this.account_idFieldSpecified;
        }
        set {
            this.account_idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal userlist_version {
        get {
            return this.userlist_versionField;
        }
        set {
            this.userlist_versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool userlist_versionSpecified {
        get {
            return this.userlist_versionFieldSpecified;
        }
        set {
            this.userlist_versionFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/userlist/3.0")]
public partial class Filters {
    
    private string custom_idField;
    
    private string first_nameField;
    
    private string last_nameField;
    
    private LoginAccountType login_account_typeField;
    
    private bool login_account_typeFieldSpecified;
    
    private string usernameField;
    
    private string email_addressField;
    
    private bool login_enabledField;
    
    private bool login_enabledFieldSpecified;
    
    private bool requires_tokenField;
    
    private bool requires_tokenFieldSpecified;
    
    private string teamsField;
    
    private string rolesField;
    
    private string allowed_ip_addressesField;
    
    private bool is_elearning_managerField;
    
    private bool is_elearning_managerFieldSpecified;
    
    private string elearning_managerField;
    
    private string elearning_trackField;
    
    private string elearning_curriculumField;
    
    private bool keep_elearning_activeField;
    
    private bool keep_elearning_activeFieldSpecified;
    
    private string titleField;
    
    private string custom_oneField;
    
    private string custom_twoField;
    
    private string custom_threeField;
    
    private string custom_fourField;
    
    private string custom_fiveField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custom_id {
        get {
            return this.custom_idField;
        }
        set {
            this.custom_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string first_name {
        get {
            return this.first_nameField;
        }
        set {
            this.first_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string last_name {
        get {
            return this.last_nameField;
        }
        set {
            this.last_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public LoginAccountType login_account_type {
        get {
            return this.login_account_typeField;
        }
        set {
            this.login_account_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool login_account_typeSpecified {
        get {
            return this.login_account_typeFieldSpecified;
        }
        set {
            this.login_account_typeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email_address {
        get {
            return this.email_addressField;
        }
        set {
            this.email_addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool login_enabled {
        get {
            return this.login_enabledField;
        }
        set {
            this.login_enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool login_enabledSpecified {
        get {
            return this.login_enabledFieldSpecified;
        }
        set {
            this.login_enabledFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool requires_token {
        get {
            return this.requires_tokenField;
        }
        set {
            this.requires_tokenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool requires_tokenSpecified {
        get {
            return this.requires_tokenFieldSpecified;
        }
        set {
            this.requires_tokenFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string teams {
        get {
            return this.teamsField;
        }
        set {
            this.teamsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string roles {
        get {
            return this.rolesField;
        }
        set {
            this.rolesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string allowed_ip_addresses {
        get {
            return this.allowed_ip_addressesField;
        }
        set {
            this.allowed_ip_addressesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool is_elearning_manager {
        get {
            return this.is_elearning_managerField;
        }
        set {
            this.is_elearning_managerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool is_elearning_managerSpecified {
        get {
            return this.is_elearning_managerFieldSpecified;
        }
        set {
            this.is_elearning_managerFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string elearning_manager {
        get {
            return this.elearning_managerField;
        }
        set {
            this.elearning_managerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string elearning_track {
        get {
            return this.elearning_trackField;
        }
        set {
            this.elearning_trackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string elearning_curriculum {
        get {
            return this.elearning_curriculumField;
        }
        set {
            this.elearning_curriculumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool keep_elearning_active {
        get {
            return this.keep_elearning_activeField;
        }
        set {
            this.keep_elearning_activeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool keep_elearning_activeSpecified {
        get {
            return this.keep_elearning_activeFieldSpecified;
        }
        set {
            this.keep_elearning_activeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custom_one {
        get {
            return this.custom_oneField;
        }
        set {
            this.custom_oneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custom_two {
        get {
            return this.custom_twoField;
        }
        set {
            this.custom_twoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custom_three {
        get {
            return this.custom_threeField;
        }
        set {
            this.custom_threeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custom_four {
        get {
            return this.custom_fourField;
        }
        set {
            this.custom_fourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custom_five {
        get {
            return this.custom_fiveField;
        }
        set {
            this.custom_fiveField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/userlist/3.0")]
public enum LoginAccountType {
    
    /// <remarks/>
    user,
    
    /// <remarks/>
    api,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="https://analysiscenter.veracode.com/schema/userlist/3.0")]
public partial class UserList {
    
    private string usernamesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string usernames {
        get {
            return this.usernamesField;
        }
        set {
            this.usernamesField = value;
        }
    }
}
